### ISSUE TITLE
App not working on Catalina

### ISSUE THREAD

**Issue by enzyme69** [fouman75/Materialize#2]
Is there anyway to update the app compile for MacOS Catalina? Thanks!

**Comment by fouman75** [comment]
This repo isn't updated anymore. I've been contributing to this one instead: https://github.com/maikramer/Materialize

Check this issue instead: https://github.com/maikramer/Materialize/issues/10

The last build I made is here: [Dropbox](https://www.dropbox.com/s/4buvficjn2tfxob/materialize_0.3.7.app.zip?dl=0)

I haven't updated my mac to Catalina yet though. Hopefully, the build will work.
